on : push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - run: node --version
      - run: npm --version
      - uses: action/checkout@v4
      - run: npm install
      - run: node app.js